project:
  type: website
  output-dir: docs

website:
  title: "Victor Zavaleta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Blogs
        href: Blogs.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

